Vagrant.configure('2') do |config|

  #############
  # Functions #
  #############

  def set_linode_override_props(override)
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'linode'
    override.vm.box_url = "https://github.com/displague/vagrant-linode/raw/master/box/linode.box"
  end

  def set_linode_provider_machine_props(provider)
    provider.api_key = ENV['LINODE_API_KEY']
    provider.distribution = 'Debian 8'
    provider.datacenter = 'fremont'
    provider.plan = 'Linode 1024'
  end

  def prvr(path)
    # path_relative_victoria_root
    return File.join("..", "..", path)
  end

  ##############
  # Definition #
  ##############

  config.vm.provision "shell", inline: "echo Hello"
  config.vm.provision :shell, path: prvr("bootstrap/bootstrap.sh")

  config.vm.provider :linode do |provider, override|
    set_linode_override_props(override)
    set_linode_provider_machine_props(provider)
    provider.label = "agent-test"
    provider.group = "test"

    # provider.planid = <int>
    # provider.paymentterm = <*1*,12,24>
    # provider.datacenterid = <int>
    # provider.image = <string>
    # provider.imageid = <int>
    # provider.kernel = <string>
    # provider.kernelid = <int>
    # provider.private_networking = <boolean>
    # provider.stackscript = <string> # Not Supported Yet
    # provider.stackscriptid = <int> # Not Supported Yet
    # provider.distributionid = <int>
  end
end
