Vagrant.configure('2') do |config|

  #############
  # Functions #
  #############

  def set_linode_override_props(override)
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'linode'
    override.vm.box_url = "https://github.com/displague/vagrant-linode/raw/master/box/linode.box"
  end

  def set_linode_provider_machine_props(provider)
    provider.api_key = ENV['LINODE_API_KEY']
    provider.distribution = 'Debian 8'
    provider.datacenter = 'fremont'
    provider.plan = 'Linode 1024'
    provider.private_networking = true
  end

  def prvr(path)
    # path_relative_victoria_root
    return File.join("..", "..", path)
  end

  def set_machine_name(machine, label, group)
    machine.vm.provider :linode do |provider, override|
      provider.label = label
      provider.group = group
    end
  end

  ##############
  # Definition #
  ##############

  ## Base
  config.vm.provider :linode do |provider, override|
    set_linode_override_props(override)
    set_linode_provider_machine_props(provider)
  end
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.provision :shell, path: prvr("bootstrap/bootstrap.sh")

  ## master
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    # master.vm.network :private_network, ip: "10.144.144.10"
    set_machine_name(master, "master", "mesos-master")
    master.vm.provision :shell, path: prvr("bootstrap/install_mesos.sh")
  end
end
